### ISSUE TITLE
Cayo components not compiled if they don't show in a page at start of dev process

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/cayo#63]
```
11:28:11 PM [vite] Internal server error: Failed to resolve import "/usr/test-cayo/.cayo/__cayo/components/Test.svelte.js" from ".cayo/cayo-runtime.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /usr/test-cayo/.cayo/cayo-runtime.js
  1  |  import Test from '/usr/test-cayo/.cayo/__cayo/components/Test.svelte.js';
     |                    ^
  2  |  
  3  |  function getProps(cayoId) {
      at formatError (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:42190:46)
      at TransformContext.error (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:42186:19)
      at normalizeUrl (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:67193:26)
      at async TransformContext.transform (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:67333:57)
      at async Object.transform (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:42397:30)
      at async doTransform (/usr/cayo/node_modules/vite/dist/node/chunks/dep-3e244802.js:56727:29)
```

**Comment by matthew-ia** [comment]
Might also be when you aren't rendering a Cayo Component, but then it gets added to a page. For some reason, it's not picking up that it was added, and running through the compilation process?

I.e., works when you restart the dev server.

**Comment by matthew-ia** [comment]
Figured out bigger problem that might make this go away if fixed: cayo components aren't pushed onto pages' and components' dependency trees, so they can't be found in dep tree to then recompile
